---

defaultMessage: >

  Please consider an alternative to `{{match}}`. 

  {{#if alternatives~}}


  Possibilities include: {{#each alternatives}}{{#if @index}},
  {{/if}}`{{this}}`{{/each}}.

  {{~/if}}

ignore:
  - .github/in-solidarity.yml

ignoreDefaults: true

rules:

  # INI Tier 1
  abort:
    regex:
      - /abort/gi
    level: failure
    alternatives:
      - user-initiated termination
      - force quit
      - cancel
      - system-initiated termination
      - fail
      - close (app, program, connection)
      - end
      - halt
      - hard stop
      - stop (something you triggered)
      - NOT kill

  whitehat:
    regex:
      - /white[\w_-]*hat/gi
    level: failure
    alternatives:
      - ethical hacker

  blackhat:
    regex:
      - /black[\w_-]*hat/gi
    level: failure
    alternatives:
      - unethical hacker
      - attacker

  cripple:
    regex:
      - /crippl/gi
    level: failure
    alternatives:
      - impacted
      - degraded
      - restricted
      - immobilised
      - broken
      - damaged
      - defective
      - deformed
      - impaired

  master:
    regex:
      - /master(?!.mind)(?!.inventor)/gi
    level: failure
    alternatives:
      - active
      - central
      - initiator
      - leader
      - main
      - orchestrator
      - parent
      - primary
      - server
      - original
      - source
      - control plane

  slave:
    regex:
      - /slave/gi
    level: failure
    alternatives:
      - follower
      - peripheral
      - replica
      - responder
      - secondary
      - standby
      - worker
      - control plane node
      - doer
      - child

  tribe:
    regex:
      - /tribe/gi
    level: failure
    alternatives:
      - team
      - squad of squads

  whitelist:
    regex:
      - /white[\w_-]*list/gi
    level: failure
    alternatives:
      - accept list
      - allowlist
      - approved list
      - pass list
      - permitted

  blacklist:
    regex:
      - /black[\w_-]*list/gi
    level: failure
    alternatives:
      - blocklist
      - denylist
      - prohibited
      - refused
      - reject list
      - unapproved list

  # INI Tier 2
  sanity-check:
    regex:
      - /sanity[\w_-]*check/gi
    level: warning
    alternatives:
      - coherence check
      - confidence check
      - quick check

  # INI Tier 3
  hallucinate:
    regex:
      - /hallucinat/gi
    level: warning
    alternatives:
      - inaccurate information
      - create inaccurate information
      - generate inaccurate information

  man-in-the-middle:
    regex:
      - /man[\w_-]*in[\w_-]*the[\w_-]*middle/gi
    level: warning
    alternatives:
      - adversary-in-the-middle
      - interceptor
      - intermediary

  segregate:
    regex:
      - /segregat/gi
    level: warning
    alternatives:
      - segment
      - separate
      - NOT discriminate

  # IETF
  grandfathered:
    regex:
      - /grandfather/gi
    level: warning
    alternatives:
      - exemption
      - historical
      - legacy status
      - pre-approved
      - special case

  gendered-terms:
    regex:
      - /chair[\w_-]*man/gi
      - /mankind/gi
      - /man[\w_-]*month/gi
      - /mans/gi
      - /man[\w_-]*made/gi
      - /man[\w_-]*power/gi
      - /guys?/gi
      - /(wo)?m[ae]n/gi
      - /(fe)?male/gi
      - /lad(y|ie)\'?s?\'?/gi
      - /(\w+m[ae]nship)/gi
    level: warning
    alternatives:
      - individual
      - people
      - person

  gendered-pronouns:
    regex:
      - /(he|him|his|she|her|hers)/gi
    level: warning
    alternatives:
      - they
      - them
      - their

  crazy:
    regex:
      - /craz(y|ie)?/gi
    level: warning
    alternatives:
      - malfunctioning
      - puzzling
      - surprising
      - unexpected

  dummy:
    regex:
      - /dummy/gi
    level: warning
    alternatives:
      - placeholder
      - sample
      - stand-in
      - substitute

  dark-pattern:
    regex:
      - /dark[\w_-]*pattern/gi
    level: warning
    alternatives:
      - deception pattern

  balkanization:
    regex:
      - /balkani[zs]/gi
    level: warning
    alternatives:
      - bifurcation
      - segmentation

  blackmail:
    regex:
      - /black[\w_-]*mail/gi
    level: warning
    alternatives:
      - extortion

  black-sheep:
    regex:
      - /black[\w_-]*sheep/gi
    level: warning
    alternatives:
      - disreputable

  black-market:
    regex:
      - /black[\w_-]*market/gi
    level: warning
    alternatives:
      - illegal marketplace

  tradition:
    regex:
      - /tradition/gi
    level: warning
    alternatives:
      - classic
      - classical
      - common
      - conventional
      - customary
      - fixed
      - habitual
      - historic
      - long-established
      - popular
      - prescribed
      - regular
      - rooted
      - time-honored
      - universal
      - widely used
      - widespread

  native:
    regex:
      - /native/gi
    level: warning
    alternatives:
      - built-in
      - fundamental
      - ingrained
      - intrinsic
      - original

  elder:
    regex:
      - /elder/gi
    level: warning
    alternatives:
      - aged
      - aging
      - old

  dumb:
    regex:
      - /dumb/gi
    level: warning
    alternatives:
      - dull
      - inarticuate
      - incoherent

  immature:
    regex:
      - /immatur/gi
    level: warning
    alternatives:
      - imperfect
      - premature
      - underdeveloped
      - unfinished
      - unsophisticated

  handicap:
    regex:
      - /handicap/gi
    level: warning
    alternatives:
      - broken
      - damaged
      - defective
      - deformed
      - impaired

  gendered-connectors:
    regex:
      - /(fe)?male[\w_-]*(connector|end)/gi
    level: warning
    alternatives:
      - plug
      - socket

  invalid:
    regex:
      - /invalid/gi
    # IETF took out after causing author confusion numerous time.
    level: off
    alternatives:
      - not valid
      - unenforceable
      - not binding
      - inoperative
      - illegitimate
      - incorrect
      - improper
      - unacceptable
      - inapplicable
      - revoked
      - rescinded

  blind:
    regex:
      - /blind/gi
    level: warning
    alternatives:
      - visually impaired
      - unmindful of
      - unconcerned about
      - negligent of
      - unaware
      - uncomprehending
      - unaware
      - uncritical
      - unthinking
      - hasty
      - blocked
      - opaque

  deaf:
    regex:
      - /deaf/gi
    level: warning
    alternatives:
      - hard of hearing
      - unmoved by
      - unaffected by
      - unconcerned with
      - oblivious to
      - indifferent to

  right:
    regex:
      - /right/gi
      # IETF took out as it occurs in the IETF boilerplate text
    level: off
    alternatives:
      - just
      - fair
      - good
      - correct
      - accurate
      - precise
      - official
      - suitable
      - ideal
      - opportune
      - fitting

  blackhole:
    regex:
      - /black[\w_-]hol/gi
    # See https://github.com/ietf/terminology/issues/31
    level: off
    alternatives:
      - drop
      - reject
      - ignore
      - disregard
      - bypass
